openapi: 3.0.0
info:
  title: User API
  description: RESTful API for user management
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
paths:
  /users:
    get:
      summary: Get all users
      responses:
        200:
          description: List of users
    post:
      summary: Create a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        201:
          description: User created
components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
      required:
        - name
        - email